language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
branches:
  only:
  - master
script:
- npm run build
deploy:
  provider: s3
  bucket: food-carts-ui
  region: us-west-2
  local_dir: static
  skip_cleanup: true
  access_key_id: AKIAJZHSIOQ7OFVE3LOA
  secret_access_key:
    secure: eijPpmjvM1V038b9iNEQRexIjc4LE3ixGlG7hjDOk9j4ttQkceebwaUD2i5BJuLwj5z2KUMlaBHM5FbY9ozKdBr0EJxW0iz8nSej/6tQ3V6JCJjzkjWF3CBxhHmfVJKb4UwNxlpGm2cE0vAO+7RK9168YPouXhEMckeqcua5MzzS7Vwzh8w73zpR7SomV6tkF1vW6c2ATnQ2sD4OMj7aSMNNZbnX/HdGtLWnr/jDlCSjAB2lFXXyCD7ZSXBjejKSxYXRngRbFeQivx5Z+pY/4uwmgThUTyfPb6vHfpveIFnHgJQzAGXEyAz/NLZ0V3pxz6r9z6f7XwOUjTQdDySFxLyfY3tH6CpkYRj6zzGtNfyb4Q8tcdCRTkecbZe0a9ndXU2q7XK7bFgPjsXTxgdQ1x1496qXqMWWE7f+ppPAvcwmE+Ci0/RiwyCBOa0uLgtXH7zwtTkmBuMWAftng5Olm3avVptD/3bOdJ8+0zWpqu0Otvle/OTjwzBvGHrn8Om7kBaH3NKlT6kR4FON9aDwsdZzN2dIWTfLqhc1qx5ncKInulswposQ6CnUDQQlHF5jJRwDEqRTFj4f/6h/SLVFq07kwR22xyIE6Org346Pq0v0T+MNQ7pZuxv6feMli6HXRh46RXnnelSWDr966Fi+hXecgB7IR0QwvkarDFoqLd4=
  acl: public_read
